// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Clipper1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fcnMainConfig(lv_event_t * e);
void fcnTxTesla(lv_event_t * e);
void fcnPresetPopDir(lv_event_t * e);
void fcnMainPreTX(lv_event_t * e);
void fcnTeslaTx(lv_event_t * e);
void fcnProtAnaCancel(lv_event_t * e);
void fcnProtAnaRxOff(lv_event_t * e);
void fcnProtAnaClear(lv_event_t * e);
void fcnProtAnaRxEn(lv_event_t * e);
void fcnProtAnaRxOff(lv_event_t * e);
void fcnGetCurfreq(lv_event_t * e);
void fcnSetFreq(lv_event_t * e);
void fcnSetFreq(lv_event_t * e);
void fcnSetPreset(lv_event_t * e);
void fcnClearPresetsFilesDD(lv_event_t * e);
void fcnPopulateFileDropdown(lv_event_t * e);
void fcnPresetTx(lv_event_t * e);
void fcnSettingsOTA(lv_event_t * e);
void fcnProtAnaCancel(lv_event_t * e);
void fcnSettingsOTA(lv_event_t * e);
void fcnTCKybdTrans(lv_event_t * e);
void fcnTCKybdFreq(lv_event_t * e);
void fcnTCKybdDev(lv_event_t * e);
void fcnConfigTx(lv_event_t * e);
void fcnKybdAlphaOk(lv_event_t * e);
void fcnKybdAlphaCncl(lv_event_t * e);
void fcnScanWifi(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
