// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Clipper1

#include "../ui.h"

void ui_scrKybdNum_screen_init(void)
{
    ui_scrKybdNum = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrKybdNum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrKybdNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrKybdNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrKybdNum, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKybdOK = lv_btn_create(ui_scrKybdNum);
    lv_obj_set_width(ui_btnKybdOK, 100);
    lv_obj_set_height(ui_btnKybdOK, 50);
    lv_obj_set_x(ui_btnKybdOK, -73);
    lv_obj_set_y(ui_btnKybdOK, 196);
    lv_obj_set_align(ui_btnKybdOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnKybdOK, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKybdOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKybdOK, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKybdOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKybdCncl = lv_btn_create(ui_scrKybdNum);
    lv_obj_set_width(ui_btnKybdCncl, 110);
    lv_obj_set_height(ui_btnKybdCncl, 50);
    lv_obj_set_x(ui_btnKybdCncl, 70);
    lv_obj_set_y(ui_btnKybdCncl, 195);
    lv_obj_set_align(ui_btnKybdCncl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnKybdCncl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKybdCncl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKybdCncl, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKybdCncl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKybdFreq = lv_textarea_create(ui_scrKybdNum);
    lv_obj_set_width(ui_txtKybdFreq, 240);
    lv_obj_set_height(ui_txtKybdFreq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtKybdFreq, 0);
    lv_obj_set_y(ui_txtKybdFreq, -177);
    lv_obj_set_align(ui_txtKybdFreq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtKybdFreq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtKybdFreq, "1234567890.");
    lv_textarea_set_max_length(ui_txtKybdFreq, 6);
    lv_textarea_set_one_line(ui_txtKybdFreq, true);
    lv_obj_set_style_text_color(ui_txtKybdFreq, lv_color_hex(0x00FF0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKybdFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKybdFreq, &ui_font_LCD30at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtKybdFreq, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtKybdFreq, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtKybdFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_txtKybdFreq, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_txtKybdFreq, lv_color_hex(0x00FF0C), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKybdFreq, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_lblKybdTitle = lv_label_create(ui_scrKybdNum);
    lv_obj_set_width(ui_lblKybdTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdTitle, 0);
    lv_obj_set_y(ui_lblKybdTitle, -220);
    lv_obj_set_align(ui_lblKybdTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdTitle, "Enter Value");
    lv_obj_set_style_text_color(ui_lblKybdTitle, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblKybdTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblKybdTitle, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdValueUnits = lv_label_create(ui_scrKybdNum);
    lv_obj_set_width(ui_lblKybdValueUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdValueUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdValueUnits, 0);
    lv_obj_set_y(ui_lblKybdValueUnits, -139);
    lv_obj_set_align(ui_lblKybdValueUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdValueUnits, "-Unit-");
    lv_obj_set_style_text_color(ui_lblKybdValueUnits, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblKybdValueUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblKybdValueUnits, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdCancel = lv_label_create(ui_scrKybdNum);
    lv_obj_set_width(ui_lblKybdCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdCancel, 71);
    lv_obj_set_y(ui_lblKybdCancel, 195);
    lv_obj_set_align(ui_lblKybdCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdCancel, "CANCEL");
    lv_obj_set_style_text_font(ui_lblKybdCancel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdOk = lv_label_create(ui_scrKybdNum);
    lv_obj_set_width(ui_lblKybdOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdOk, -75);
    lv_obj_set_y(ui_lblKybdOk, 196);
    lv_obj_set_align(ui_lblKybdOk, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdOk, "OK");
    lv_obj_set_style_text_font(ui_lblKybdOk, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KybdNumeric = lv_keyboard_create(ui_scrKybdNum);
    lv_keyboard_set_mode(ui_KybdNumeric, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KybdNumeric, 300);
    lv_obj_set_height(ui_KybdNumeric, 205);
    lv_obj_set_x(ui_KybdNumeric, 0);
    lv_obj_set_y(ui_KybdNumeric, 38);
    lv_obj_set_align(ui_KybdNumeric, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_KybdNumeric, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_KybdNumeric, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnKybdOK, ui_event_btnKybdOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnKybdCncl, ui_event_btnKybdCncl, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KybdNumeric, ui_txtKybdFreq);
    lv_obj_add_event_cb(ui_KybdNumeric, ui_event_KybdNumeric, LV_EVENT_ALL, NULL);

}
