// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Clipper1

#include "../ui.h"

void ui_scrCC1101Scan_screen_init(void)
{
    ui_scrCC1101Scan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrCC1101Scan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrCC1101Scan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrCC1101Scan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_scrCC1101Scan, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWApps1 = lv_label_create(ui_scrCC1101Scan);
    lv_obj_set_width(ui_lblRCSWApps1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWApps1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWApps1, 0);
    lv_obj_set_y(ui_lblRCSWApps1, -220);
    lv_obj_set_align(ui_lblRCSWApps1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWApps1, "CC1101 SCANNER");
    lv_obj_set_style_text_color(ui_lblRCSWApps1, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWApps1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWApps1, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tabCC1101Scan = lv_tabview_create(ui_scrCC1101Scan, LV_DIR_BOTTOM, 50);
    lv_obj_set_width(ui_tabCC1101Scan, 320);
    lv_obj_set_height(ui_tabCC1101Scan, 365);
    lv_obj_set_x(ui_tabCC1101Scan, 0);
    lv_obj_set_y(ui_tabCC1101Scan, -23);
    lv_obj_set_align(ui_tabCC1101Scan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tabCC1101Scan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tabCC1101Scan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tabCC1101Scan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_tabCC1101Scan), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_tabCC1101Scan), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_tabCC1101Scan), &ui_font_Verdana18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_tabCC1101Scan), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_tabCC1101Scan), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scanner = lv_tabview_add_tab(ui_tabCC1101Scan, "Scanner");

    ui_txtScannerData = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScannerData, 153);
    lv_obj_set_height(ui_txtScannerData, 153);
    lv_obj_set_x(ui_txtScannerData, -66);
    lv_obj_set_y(ui_txtScannerData, 68);
    lv_obj_set_align(ui_txtScannerData, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtScannerData, "Signals Marked...");

    ui_txtScanStartFq = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScanStartFq, 120);
    lv_obj_set_height(ui_txtScanStartFq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtScanStartFq, -33);
    lv_obj_set_y(ui_txtScanStartFq, -129);
    lv_obj_set_align(ui_txtScanStartFq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtScanStartFq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtScanStartFq, "1234567890.");
    lv_textarea_set_max_length(ui_txtScanStartFq, 6);
    lv_textarea_set_text(ui_txtScanStartFq, "434.00");
    lv_textarea_set_one_line(ui_txtScanStartFq, true);
    lv_obj_set_style_text_color(ui_txtScanStartFq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtScanStartFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtScanStartFq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtScanStartFq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtScanStopFq = lv_textarea_create(ui_Scanner);
    lv_obj_set_width(ui_txtScanStopFq, 120);
    lv_obj_set_height(ui_txtScanStopFq, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtScanStopFq, -32);
    lv_obj_set_y(ui_txtScanStopFq, -86);
    lv_obj_set_align(ui_txtScanStopFq, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtScanStopFq, NULL);
    else lv_textarea_set_accepted_chars(ui_txtScanStopFq, "1234567890.");
    lv_textarea_set_max_length(ui_txtScanStopFq, 6);
    lv_textarea_set_text(ui_txtScanStopFq, "435.00");
    lv_textarea_set_one_line(ui_txtScanStopFq, true);
    lv_obj_set_style_text_color(ui_txtScanStopFq, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtScanStopFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtScanStopFq, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtScanStopFq, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScanStartFq = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScanStartFq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanStartFq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScanStartFq, -126);
    lv_obj_set_y(ui_lblScanStartFq, -130);
    lv_obj_set_align(ui_lblScanStartFq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanStartFq, "START\nMHZ");
    lv_obj_set_style_text_color(ui_lblScanStartFq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanStartFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblScanStartFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScanStopFq = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScanStopFq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanStopFq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScanStopFq, -126);
    lv_obj_set_y(ui_lblScanStopFq, -87);
    lv_obj_set_align(ui_lblScanStopFq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanStopFq, "STOP\nMHZ");
    lv_obj_set_style_text_color(ui_lblScanStopFq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanStopFq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblScanStopFq, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swScannerOn = lv_switch_create(ui_Scanner);
    lv_obj_set_width(ui_swScannerOn, 70);
    lv_obj_set_height(ui_swScannerOn, 25);
    lv_obj_set_x(ui_swScannerOn, 96);
    lv_obj_set_y(ui_swScannerOn, 24);
    lv_obj_set_align(ui_swScannerOn, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 95);
    lv_obj_set_y(ui_Label2, 1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "ENABLE");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnScannerClear = lv_btn_create(ui_Scanner);
    lv_obj_set_width(ui_btnScannerClear, 70);
    lv_obj_set_height(ui_btnScannerClear, 27);
    lv_obj_set_x(ui_btnScannerClear, 98);
    lv_obj_set_y(ui_btnScannerClear, 95);
    lv_obj_set_align(ui_btnScannerClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnScannerClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnScannerClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblScannerClear = lv_label_create(ui_btnScannerClear);
    lv_obj_set_width(ui_lblScannerClear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerClear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerClear, -1);
    lv_obj_set_y(ui_lblScannerClear, 1);
    lv_obj_set_align(ui_lblScannerClear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerClear, "CLEAR");

    ui_sldThreshold = lv_slider_create(ui_Scanner);
    lv_slider_set_range(ui_sldThreshold, -80, -10);
    lv_slider_set_value(ui_sldThreshold, -74, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldThreshold) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldThreshold, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_sldThreshold, 140);
    lv_obj_set_height(ui_sldThreshold, 19);
    lv_obj_set_x(ui_sldThreshold, -69);
    lv_obj_set_y(ui_sldThreshold, -29);
    lv_obj_set_align(ui_sldThreshold, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0x7E7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sldThreshold, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldThreshold, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_sldThreshold, &ui_img_needle_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblSldThreshold = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblSldThreshold, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSldThreshold, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSldThreshold, -97);
    lv_obj_set_y(ui_lblSldThreshold, -52);
    lv_obj_set_align(ui_lblSldThreshold, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSldThreshold, "THRESHOLD");
    lv_obj_set_style_text_color(ui_lblSldThreshold, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSldThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblThreshold = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblThreshold, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblThreshold, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblThreshold, 29);
    lv_obj_set_y(ui_lblThreshold, -28);
    lv_obj_set_align(ui_lblThreshold, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblThreshold, "-74");
    lv_obj_set_style_text_color(ui_lblThreshold, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblThreshold, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblThreshold, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcScanBW = lv_arc_create(ui_Scanner);
    lv_obj_set_width(ui_arcScanBW, 77);
    lv_obj_set_height(ui_arcScanBW, 77);
    lv_obj_set_x(ui_arcScanBW, 89);
    lv_obj_set_y(ui_arcScanBW, -93);
    lv_obj_set_align(ui_arcScanBW, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcScanBW, 58, 812);
    lv_obj_set_style_bg_color(ui_arcScanBW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcScanBW, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcScanBW, lv_color_hex(0xF2FF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcScanBW, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_arcScanBW, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcScanBW, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcScanBW, 2, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblScannerBWArc = lv_label_create(ui_arcScanBW);
    lv_obj_set_width(ui_lblScannerBWArc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerBWArc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerBWArc, -1);
    lv_obj_set_y(ui_lblScannerBWArc, 0);
    lv_obj_set_align(ui_lblScannerBWArc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerBWArc, "58");
    lv_obj_set_style_text_color(ui_lblScannerBWArc, lv_color_hex(0xF4FB00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScannerBWArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScannerBWArc, &ui_font_Verdana24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScannerBW = lv_label_create(ui_Scanner);
    lv_obj_set_width(ui_lblScannerBW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScannerBW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblScannerBW, 87);
    lv_obj_set_y(ui_lblScannerBW, -141);
    lv_obj_set_align(ui_lblScannerBW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScannerBW, "BANDWIDTH");
    lv_obj_set_style_text_color(ui_lblScannerBW, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScannerBW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScannerBW, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config = lv_tabview_add_tab(ui_tabCC1101Scan, "Config");

    ui_btnScanBack = lv_btn_create(ui_scrCC1101Scan);
    lv_obj_set_width(ui_btnScanBack, 110);
    lv_obj_set_height(ui_btnScanBack, 50);
    lv_obj_set_x(ui_btnScanBack, -73);
    lv_obj_set_y(ui_btnScanBack, 200);
    lv_obj_set_align(ui_btnScanBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnScanBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnScanBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnScanBack, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnScanBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblScanBack = lv_label_create(ui_btnScanBack);
    lv_obj_set_width(ui_lblScanBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblScanBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblScanBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblScanBack, "BACK");
    lv_obj_set_style_text_color(ui_lblScanBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblScanBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblScanBack, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_txtScanStartFq, ui_event_txtScanStartFq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtScanStopFq, ui_event_txtScanStopFq, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_swScannerOn, ui_event_swScannerOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnScannerClear, ui_event_btnScannerClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldThreshold, ui_event_sldThreshold, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_arcScanBW, ui_event_arcScanBW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnScanBack, ui_event_btnScanBack, LV_EVENT_ALL, NULL);

}
