// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Clipper1

#include "../ui.h"

void ui_scrRCSWTenPole_screen_init(void)
{
    ui_scrRCSWTenPole = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRCSWTenPole, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrRCSWTenPole, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrRCSWTenPole, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSW10Pole = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblRCSW10Pole, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSW10Pole, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSW10Pole, 0);
    lv_obj_set_y(ui_lblRCSW10Pole, -220);
    lv_obj_set_align(ui_lblRCSW10Pole, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSW10Pole, "10 POLE - RECEPTACLES");
    lv_obj_set_style_text_color(ui_lblRCSW10Pole, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSW10Pole, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSW10Pole, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackToRCSW = lv_btn_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_btnBackToRCSW, 92);
    lv_obj_set_height(ui_btnBackToRCSW, 62);
    lv_obj_set_x(ui_btnBackToRCSW, -105);
    lv_obj_set_y(ui_btnBackToRCSW, 197);
    lv_obj_set_align(ui_btnBackToRCSW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBackToRCSW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBackToRCSW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnBackToRCSW, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBackToRCSW, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackToRCSW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnBackToRCSW, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnBackToRCSW, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBackToRCSW = lv_label_create(ui_btnBackToRCSW);
    lv_obj_set_width(ui_lblBackToRCSW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBackToRCSW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBackToRCSW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBackToRCSW, "< BACK");
    lv_obj_set_style_text_align(ui_lblBackToRCSW, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBackToRCSW, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTenPoleTxOn = lv_btn_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_btnTenPoleTxOn, 80);
    lv_obj_set_height(ui_btnTenPoleTxOn, 60);
    lv_obj_set_x(ui_btnTenPoleTxOn, 10);
    lv_obj_set_y(ui_btnTenPoleTxOn, 196);
    lv_obj_set_align(ui_btnTenPoleTxOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTenPoleTxOn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTenPoleTxOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTenPoleTxOn, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTenPoleTxOn, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTenPoleTxOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnTenPoleTxOn, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnTenPoleTxOn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTenPoleTxOn = lv_label_create(ui_btnTenPoleTxOn);
    lv_obj_set_width(ui_lblTenPoleTxOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTenPoleTxOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTenPoleTxOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTenPoleTxOn, "ON");
    lv_obj_set_style_text_align(ui_lblTenPoleTxOn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTenPoleTxOn, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TenPoleSW0 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW0, 58);
    lv_obj_set_height(ui_TenPoleSW0, 25);
    lv_obj_set_x(ui_TenPoleSW0, -112);
    lv_obj_set_y(ui_TenPoleSW0, -177);
    lv_obj_set_align(ui_TenPoleSW0, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW0, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW0, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW0, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW0, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW1 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW1, 58);
    lv_obj_set_height(ui_TenPoleSW1, 25);
    lv_obj_set_x(ui_TenPoleSW1, -112);
    lv_obj_set_y(ui_TenPoleSW1, -142);
    lv_obj_set_align(ui_TenPoleSW1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW1, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW2 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW2, 58);
    lv_obj_set_height(ui_TenPoleSW2, 25);
    lv_obj_set_x(ui_TenPoleSW2, -112);
    lv_obj_set_y(ui_TenPoleSW2, -108);
    lv_obj_set_align(ui_TenPoleSW2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW2, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW2, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW3 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW3, 58);
    lv_obj_set_height(ui_TenPoleSW3, 25);
    lv_obj_set_x(ui_TenPoleSW3, -112);
    lv_obj_set_y(ui_TenPoleSW3, -74);
    lv_obj_set_align(ui_TenPoleSW3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW3, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW3, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW4 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW4, 58);
    lv_obj_set_height(ui_TenPoleSW4, 25);
    lv_obj_set_x(ui_TenPoleSW4, -112);
    lv_obj_set_y(ui_TenPoleSW4, -40);
    lv_obj_set_align(ui_TenPoleSW4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW4, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW4, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW5 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW5, 58);
    lv_obj_set_height(ui_TenPoleSW5, 25);
    lv_obj_set_x(ui_TenPoleSW5, -112);
    lv_obj_set_y(ui_TenPoleSW5, -6);
    lv_obj_set_align(ui_TenPoleSW5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW5, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW5, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW6 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW6, 58);
    lv_obj_set_height(ui_TenPoleSW6, 25);
    lv_obj_set_x(ui_TenPoleSW6, -111);
    lv_obj_set_y(ui_TenPoleSW6, 28);
    lv_obj_set_align(ui_TenPoleSW6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW6, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW6, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW7 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW7, 58);
    lv_obj_set_height(ui_TenPoleSW7, 25);
    lv_obj_set_x(ui_TenPoleSW7, -112);
    lv_obj_set_y(ui_TenPoleSW7, 62);
    lv_obj_set_align(ui_TenPoleSW7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW7, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW7, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW7, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW8 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW8, 58);
    lv_obj_set_height(ui_TenPoleSW8, 25);
    lv_obj_set_x(ui_TenPoleSW8, -112);
    lv_obj_set_y(ui_TenPoleSW8, 96);
    lv_obj_set_align(ui_TenPoleSW8, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW8, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW8, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW8, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TenPoleSW9 = lv_switch_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_TenPoleSW9, 58);
    lv_obj_set_height(ui_TenPoleSW9, 25);
    lv_obj_set_x(ui_TenPoleSW9, -112);
    lv_obj_set_y(ui_TenPoleSW9, 130);
    lv_obj_set_align(ui_TenPoleSW9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TenPoleSW9, LV_STATE_USER_1);       /// States
    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TenPoleSW9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TenPoleSW9, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TenPoleSW9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lblBit0 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit0, -48);
    lv_obj_set_y(ui_lblBit0, -176);
    lv_obj_set_align(ui_lblBit0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit0, "0");
    lv_obj_set_style_text_color(ui_lblBit0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit0, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit1 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit1, -48);
    lv_obj_set_y(ui_lblBit1, -142);
    lv_obj_set_align(ui_lblBit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit1, "0");
    lv_obj_set_style_text_color(ui_lblBit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit1, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit2 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit2, -48);
    lv_obj_set_y(ui_lblBit2, -109);
    lv_obj_set_align(ui_lblBit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit2, "0");
    lv_obj_set_style_text_color(ui_lblBit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit2, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit3 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit3, -48);
    lv_obj_set_y(ui_lblBit3, -76);
    lv_obj_set_align(ui_lblBit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit3, "0");
    lv_obj_set_style_text_color(ui_lblBit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit3, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit4 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit4, -48);
    lv_obj_set_y(ui_lblBit4, -41);
    lv_obj_set_align(ui_lblBit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit4, "0");
    lv_obj_set_style_text_color(ui_lblBit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit4, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit5 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit5, -48);
    lv_obj_set_y(ui_lblBit5, -7);
    lv_obj_set_align(ui_lblBit5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit5, "0");
    lv_obj_set_style_text_color(ui_lblBit5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit5, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit6 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit6, -48);
    lv_obj_set_y(ui_lblBit6, 27);
    lv_obj_set_align(ui_lblBit6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit6, "0");
    lv_obj_set_style_text_color(ui_lblBit6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit6, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit7 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit7, -48);
    lv_obj_set_y(ui_lblBit7, 61);
    lv_obj_set_align(ui_lblBit7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit7, "0");
    lv_obj_set_style_text_color(ui_lblBit7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit7, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit8 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit8, -48);
    lv_obj_set_y(ui_lblBit8, 95);
    lv_obj_set_align(ui_lblBit8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit8, "0");
    lv_obj_set_style_text_color(ui_lblBit8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit8, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBit9 = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblBit9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBit9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBit9, -48);
    lv_obj_set_y(ui_lblBit9, 129);
    lv_obj_set_align(ui_lblBit9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBit9, "0");
    lv_obj_set_style_text_color(ui_lblBit9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBit9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBit9, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTenPoleTxOn1 = lv_btn_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_btnTenPoleTxOn1, 80);
    lv_obj_set_height(ui_btnTenPoleTxOn1, 60);
    lv_obj_set_x(ui_btnTenPoleTxOn1, 107);
    lv_obj_set_y(ui_btnTenPoleTxOn1, 194);
    lv_obj_set_align(ui_btnTenPoleTxOn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTenPoleTxOn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTenPoleTxOn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTenPoleTxOn1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTenPoleTxOn1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTenPoleTxOn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnTenPoleTxOn1, lv_color_hex(0x3F882F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnTenPoleTxOn1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTenPoleTxOn1 = lv_label_create(ui_btnTenPoleTxOn1);
    lv_obj_set_width(ui_lblTenPoleTxOn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTenPoleTxOn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTenPoleTxOn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTenPoleTxOn1, "OFF");
    lv_obj_set_style_text_align(ui_lblTenPoleTxOn1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTenPoleTxOn1, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRCSWStatus = lv_label_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_lblRCSWStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWStatus, 66);
    lv_obj_set_y(ui_lblRCSWStatus, -77);
    lv_obj_set_align(ui_lblRCSWStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWStatus, "-");
    lv_obj_set_style_text_color(ui_lblRCSWStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblRCSWStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWStatus, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMainFreq1 = lv_textarea_create(ui_scrRCSWTenPole);
    lv_obj_set_width(ui_txtMainFreq1, 173);
    lv_obj_set_height(ui_txtMainFreq1, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtMainFreq1, 65);
    lv_obj_set_y(ui_txtMainFreq1, -172);
    lv_obj_set_align(ui_txtMainFreq1, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtMainFreq1, NULL);
    else lv_textarea_set_accepted_chars(ui_txtMainFreq1, "1234567890.");
    lv_textarea_set_max_length(ui_txtMainFreq1, 6);
    lv_textarea_set_text(ui_txtMainFreq1, "433.92");
    lv_textarea_set_one_line(ui_txtMainFreq1, true);
    lv_obj_set_style_text_color(ui_txtMainFreq1, lv_color_hex(0x00FFEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtMainFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_txtMainFreq1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtMainFreq1, &ui_font_LCD20at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtMainFreq1, lv_color_hex(0x525052), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtMainFreq1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlTenProto = lv_dropdown_create(ui_scrRCSWTenPole);
    lv_dropdown_set_options(ui_ddlTenProto, "10 Bit Outlet\n8 Bit ProtX");
    lv_obj_set_width(ui_ddlTenProto, 150);
    lv_obj_set_height(ui_ddlTenProto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlTenProto, 65);
    lv_obj_set_y(ui_ddlTenProto, -120);
    lv_obj_set_align(ui_ddlTenProto, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlTenProto, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_btnBackToRCSW, ui_event_btnBackToRCSW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTenPoleTxOn, ui_event_btnTenPoleTxOn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW0, ui_event_TenPoleSW0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW1, ui_event_TenPoleSW1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW2, ui_event_TenPoleSW2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW3, ui_event_TenPoleSW3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW4, ui_event_TenPoleSW4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW5, ui_event_TenPoleSW5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW6, ui_event_TenPoleSW6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW7, ui_event_TenPoleSW7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW8, ui_event_TenPoleSW8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TenPoleSW9, ui_event_TenPoleSW9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnTenPoleTxOn1, ui_event_btnTenPoleTxOn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtMainFreq1, ui_event_txtMainFreq1, LV_EVENT_ALL, NULL);

}
