// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Clipper1

#include "../ui.h"

void ui_scrRCSWMain_screen_init(void)
{
    ui_scrRCSWMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRCSWMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgRCSWBtns = lv_img_create(ui_scrRCSWMain);
    lv_img_set_src(ui_imgRCSWBtns, &ui_img_mainbackground_png);
    lv_obj_set_width(ui_imgRCSWBtns, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_imgRCSWBtns, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_imgRCSWBtns, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRCSWBtns, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgRCSWBtns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblRCSWMain = lv_label_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_lblRCSWMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRCSWMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRCSWMain, 0);
    lv_obj_set_y(ui_lblRCSWMain, -220);
    lv_obj_set_align(ui_lblRCSWMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRCSWMain, "RC SWITCH APPS");
    lv_obj_set_style_text_color(ui_lblRCSWMain, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRCSWMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRCSWMain, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiBackToMain1 = lv_btn_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_btnWifiBackToMain1, 92);
    lv_obj_set_height(ui_btnWifiBackToMain1, 62);
    lv_obj_set_x(ui_btnWifiBackToMain1, -105);
    lv_obj_set_y(ui_btnWifiBackToMain1, 197);
    lv_obj_set_align(ui_btnWifiBackToMain1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiBackToMain1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiBackToMain1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWifiBackToMain1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifiBackToMain1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiBackToMain1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnWifiBackToMain1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnWifiBackToMain1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_btnWifiBackToMain1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "BACK TO\nMAIN");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiScanner1 = lv_btn_create(ui_scrRCSWMain);
    lv_obj_set_width(ui_btnWifiScanner1, 92);
    lv_obj_set_height(ui_btnWifiScanner1, 62);
    lv_obj_set_x(ui_btnWifiScanner1, 106);
    lv_obj_set_y(ui_btnWifiScanner1, 197);
    lv_obj_set_align(ui_btnWifiScanner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiScanner1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiScanner1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWifiScanner1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifiScanner1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiScanner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnWifiScanner1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnWifiScanner1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiScanner1 = lv_label_create(ui_btnWifiScanner1);
    lv_obj_set_width(ui_lblWifiScanner1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiScanner1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiScanner1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiScanner1, "10\nPOLE\nRECEP");
    lv_obj_set_style_text_align(ui_lblWifiScanner1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiScanner1, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnWifiBackToMain1, ui_event_btnWifiBackToMain1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiScanner1, ui_event_btnWifiScanner1, LV_EVENT_ALL, NULL);

}
