// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Clipper1

#include "../ui.h"

void ui_scrWifiApps_screen_init(void)
{
    ui_scrWifiApps = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrWifiApps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_scrWifiApps, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_scrWifiApps);

    ui_imgWifiBtns = lv_img_create(ui_scrWifiApps);
    lv_img_set_src(ui_imgWifiBtns, &ui_img_mainbackground_png);
    lv_obj_set_width(ui_imgWifiBtns, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_imgWifiBtns, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_imgWifiBtns, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifiBtns, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgWifiBtns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWifiMain = lv_label_create(ui_scrWifiApps);
    lv_obj_set_width(ui_lblWifiMain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiMain, 0);
    lv_obj_set_y(ui_lblWifiMain, -220);
    lv_obj_set_align(ui_lblWifiMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiMain, "WIFI APPLICATIONS");
    lv_obj_set_style_text_color(ui_lblWifiMain, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiMain, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiBackToMain = lv_btn_create(ui_scrWifiApps);
    lv_obj_set_width(ui_btnWifiBackToMain, 92);
    lv_obj_set_height(ui_btnWifiBackToMain, 62);
    lv_obj_set_x(ui_btnWifiBackToMain, -105);
    lv_obj_set_y(ui_btnWifiBackToMain, 197);
    lv_obj_set_align(ui_btnWifiBackToMain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiBackToMain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiBackToMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWifiBackToMain, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifiBackToMain, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiBackToMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnWifiBackToMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnWifiBackToMain, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_btnWifiBackToMain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "BACK TO\nMAIN");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWifiScanner = lv_btn_create(ui_scrWifiApps);
    lv_obj_set_width(ui_btnWifiScanner, 92);
    lv_obj_set_height(ui_btnWifiScanner, 62);
    lv_obj_set_x(ui_btnWifiScanner, 106);
    lv_obj_set_y(ui_btnWifiScanner, 197);
    lv_obj_set_align(ui_btnWifiScanner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWifiScanner, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWifiScanner, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWifiScanner, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWifiScanner, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWifiScanner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnWifiScanner, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnWifiScanner, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiScanner = lv_label_create(ui_btnWifiScanner);
    lv_obj_set_width(ui_lblWifiScanner, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiScanner, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiScanner, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiScanner, "WiFi\nSCANNER");
    lv_obj_set_style_text_align(ui_lblWifiScanner, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiScanner, &ui_font_Verdana14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnWifiBackToMain, ui_event_btnWifiBackToMain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifiScanner, ui_event_btnWifiScanner, LV_EVENT_ALL, NULL);

}
