// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Clipper1

#include "../ui.h"

void ui_scrConfig_screen_init(void)
{
    ui_scrConfig = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrConfig, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -125);
    lv_obj_set_y(ui_Label6, -182);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Module:");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlConfigModule = lv_dropdown_create(ui_scrConfig);
    lv_dropdown_set_options(ui_ddlConfigModule, "\nModule 1\nModule 2\nModule 3\n");
    lv_obj_set_width(ui_ddlConfigModule, 150);
    lv_obj_set_height(ui_ddlConfigModule, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlConfigModule, -77);
    lv_obj_set_y(ui_ddlConfigModule, -153);
    lv_obj_set_align(ui_ddlConfigModule, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlConfigModule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddlConfigModule), &ui_font_Verdana11,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -98);
    lv_obj_set_y(ui_Label5, -119);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Modulation Type:");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ddlConfigModulation = lv_dropdown_create(ui_scrConfig);
    lv_dropdown_set_options(ui_ddlConfigModulation, "\n2-FSK\nGFSK\nASK/OOK\n4-FSK\nMSK\n4-FSK\n");
    lv_obj_set_width(ui_ddlConfigModulation, 150);
    lv_obj_set_height(ui_ddlConfigModulation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ddlConfigModulation, -76);
    lv_obj_set_y(ui_ddlConfigModulation, -90);
    lv_obj_set_align(ui_ddlConfigModulation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ddlConfigModulation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ddlConfigModulation), &ui_font_Verdana11,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -106);
    lv_obj_set_y(ui_Label8, -56);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Transmissions:");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtConfigTransmissions = lv_textarea_create(ui_scrConfig);
    lv_obj_set_width(ui_txtConfigTransmissions, 150);
    lv_obj_set_height(ui_txtConfigTransmissions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtConfigTransmissions, -77);
    lv_obj_set_y(ui_txtConfigTransmissions, -30);
    lv_obj_set_align(ui_txtConfigTransmissions, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_txtConfigTransmissions, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_txtConfigTransmissions, &ui_font_Verdana11, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -115);
    lv_obj_set_y(ui_Label9, 4);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Frequency:");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtConfigFrequency = lv_textarea_create(ui_scrConfig);
    lv_obj_set_width(ui_txtConfigFrequency, 150);
    lv_obj_set_height(ui_txtConfigFrequency, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtConfigFrequency, -77);
    lv_obj_set_y(ui_txtConfigFrequency, 33);
    lv_obj_set_align(ui_txtConfigFrequency, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_txtConfigFrequency, &ui_font_Verdana12, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_txtConfigFrequency, &ui_font_Verdana11, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -119);
    lv_obj_set_y(ui_Label10, 130);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Raw Data:");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtConfigRawData = lv_textarea_create(ui_scrConfig);
    lv_obj_set_width(ui_txtConfigRawData, 299);
    lv_obj_set_height(ui_txtConfigRawData, 55);
    lv_obj_set_x(ui_txtConfigRawData, -1);
    lv_obj_set_y(ui_txtConfigRawData, 168);
    lv_obj_set_align(ui_txtConfigRawData, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_txtConfigRawData, &ui_font_Verdana12, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_txtConfigRawData, &ui_font_Verdana12, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -120);
    lv_obj_set_y(ui_Label11, 66);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Deviation:");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Verdana12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtConfigDeviation = lv_textarea_create(ui_scrConfig);
    lv_obj_set_width(ui_txtConfigDeviation, 150);
    lv_obj_set_height(ui_txtConfigDeviation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtConfigDeviation, -76);
    lv_obj_set_y(ui_txtConfigDeviation, 94);
    lv_obj_set_align(ui_txtConfigDeviation, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_txtConfigDeviation, &ui_font_Verdana12, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_txtConfigDeviation, &ui_font_Verdana11, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_btnConfigTX = lv_btn_create(ui_scrConfig);
    lv_obj_set_width(ui_btnConfigTX, 100);
    lv_obj_set_height(ui_btnConfigTX, 130);
    lv_obj_set_x(ui_btnConfigTX, 85);
    lv_obj_set_y(ui_btnConfigTX, -109);
    lv_obj_set_align(ui_btnConfigTX, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnConfigTX, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfigTX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfigTX, lv_color_hex(0xFC0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfigTX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConfigTX = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_lblConfigTX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblConfigTX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblConfigTX, 84);
    lv_obj_set_y(ui_lblConfigTX, -109);
    lv_obj_set_align(ui_lblConfigTX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConfigTX, "TX");
    lv_obj_set_style_text_color(ui_lblConfigTX, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblConfigTX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConfigTX, &ui_font_Verdana24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiMain2 = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_lblWifiMain2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiMain2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiMain2, 0);
    lv_obj_set_y(ui_lblWifiMain2, -220);
    lv_obj_set_align(ui_lblWifiMain2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiMain2, "TRANSMIT CONFIG");
    lv_label_set_recolor(ui_lblWifiMain2, "true");
    lv_obj_set_style_text_color(ui_lblWifiMain2, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiMain2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWifiMain2, &ui_font_Verdana18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnConfigBack = lv_btn_create(ui_scrConfig);
    lv_obj_set_width(ui_btnConfigBack, 100);
    lv_obj_set_height(ui_btnConfigBack, 53);
    lv_obj_set_x(ui_btnConfigBack, 82);
    lv_obj_set_y(ui_btnConfigBack, 56);
    lv_obj_set_align(ui_btnConfigBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnConfigBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnConfigBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnConfigBack, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnConfigBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblConfigBack = lv_label_create(ui_scrConfig);
    lv_obj_set_width(ui_lblConfigBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblConfigBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblConfigBack, 82);
    lv_obj_set_y(ui_lblConfigBack, 58);
    lv_obj_set_align(ui_lblConfigBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblConfigBack, "BACK");
    lv_obj_set_style_text_color(ui_lblConfigBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblConfigBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblConfigBack, &ui_font_Verdana24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_txtConfigTransmissions, ui_event_txtConfigTransmissions, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtConfigFrequency, ui_event_txtConfigFrequency, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtConfigRawData, ui_event_txtConfigRawData, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtConfigDeviation, ui_event_txtConfigDeviation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConfigTX, ui_event_btnConfigTX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnConfigBack, ui_event_btnConfigBack, LV_EVENT_ALL, NULL);

}
