// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Clipper1

#include "../ui.h"

void ui_scrKybdAlpha_screen_init(void)
{
    ui_scrKybdAlpha = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrKybdAlpha, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrKybdAlpha, &ui_img_blankpgbkgnd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKybdOK1 = lv_btn_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_btnKybdOK1, 100);
    lv_obj_set_height(ui_btnKybdOK1, 50);
    lv_obj_set_x(ui_btnKybdOK1, -73);
    lv_obj_set_y(ui_btnKybdOK1, 196);
    lv_obj_set_align(ui_btnKybdOK1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnKybdOK1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKybdOK1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKybdOK1, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKybdOK1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnKybdCncl1 = lv_btn_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_btnKybdCncl1, 110);
    lv_obj_set_height(ui_btnKybdCncl1, 50);
    lv_obj_set_x(ui_btnKybdCncl1, 70);
    lv_obj_set_y(ui_btnKybdCncl1, 195);
    lv_obj_set_align(ui_btnKybdCncl1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnKybdCncl1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnKybdCncl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnKybdCncl1, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnKybdCncl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKybdAlphaValue = lv_textarea_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_txtKybdAlphaValue, 240);
    lv_obj_set_height(ui_txtKybdAlphaValue, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_txtKybdAlphaValue, 0);
    lv_obj_set_y(ui_txtKybdAlphaValue, -177);
    lv_obj_set_align(ui_txtKybdAlphaValue, LV_ALIGN_CENTER);
    if("1234567890." == "") lv_textarea_set_accepted_chars(ui_txtKybdAlphaValue, NULL);
    else lv_textarea_set_accepted_chars(ui_txtKybdAlphaValue, "1234567890.");
    lv_textarea_set_max_length(ui_txtKybdAlphaValue, 6);
    lv_textarea_set_one_line(ui_txtKybdAlphaValue, true);
    lv_obj_set_style_text_color(ui_txtKybdAlphaValue, lv_color_hex(0x00FF0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKybdAlphaValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKybdAlphaValue, &ui_font_LCD30at8BPP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_txtKybdAlphaValue, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_txtKybdAlphaValue, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtKybdAlphaValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_txtKybdAlphaValue, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_txtKybdAlphaValue, lv_color_hex(0x00FF0C),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKybdAlphaValue, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_lblKybdAlphaTitle = lv_label_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_lblKybdAlphaTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdAlphaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdAlphaTitle, 0);
    lv_obj_set_y(ui_lblKybdAlphaTitle, -220);
    lv_obj_set_align(ui_lblKybdAlphaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdAlphaTitle, "Enter Value");
    lv_obj_set_style_text_color(ui_lblKybdAlphaTitle, lv_color_hex(0xFF9100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblKybdAlphaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblKybdAlphaTitle, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdAlphaInfo = lv_label_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_lblKybdAlphaInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdAlphaInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdAlphaInfo, 0);
    lv_obj_set_y(ui_lblKybdAlphaInfo, -139);
    lv_obj_set_align(ui_lblKybdAlphaInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdAlphaInfo, "-Unit-");
    lv_obj_set_style_text_color(ui_lblKybdAlphaInfo, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblKybdAlphaInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblKybdAlphaInfo, &ui_font_Verdana16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdCancel1 = lv_label_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_lblKybdCancel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdCancel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdCancel1, 71);
    lv_obj_set_y(ui_lblKybdCancel1, 195);
    lv_obj_set_align(ui_lblKybdCancel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdCancel1, "CANCEL");
    lv_obj_set_style_text_font(ui_lblKybdCancel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKybdOk1 = lv_label_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_lblKybdOk1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKybdOk1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKybdOk1, -75);
    lv_obj_set_y(ui_lblKybdOk1, 196);
    lv_obj_set_align(ui_lblKybdOk1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKybdOk1, "OK");
    lv_obj_set_style_text_font(ui_lblKybdOk1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_scrKybdAlpha);
    lv_obj_set_width(ui_Keyboard1, 311);
    lv_obj_set_height(ui_Keyboard1, 199);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 50);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_btnKybdOK1, ui_event_btnKybdOK1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnKybdCncl1, ui_event_btnKybdCncl1, LV_EVENT_ALL, NULL);

}
